// Hardcoded daily motivation for CA students — picked by day-of-year, no admin
// needed. Mostly motivational/discipline/exam-mindset, with a few study & wellness
// nudges. Add more lines anytime; the list cycles by day.
export const MOTIVATION: string[] = [
  "Discipline beats motivation — show up even on the days you don't feel like it.",
  "You don't have to be brilliant today, just consistent.",
  "One topic done well today is worth more than ten skimmed.",
  "The exam rewards the student who practised, not the one who only read.",
  "Small daily progress compounds into a rank you'll be proud of.",
  "Hard now, easy later. Easy now, hard later. Choose.",
  "Your future self is built by what you do this week.",
  "Don't count the days; make the days count.",
  "Every great CA was once a student who refused to quit.",
  "Tired is not a reason to stop — it's proof you're working.",
  "Focus on the next page, not the whole syllabus.",
  "Consistency is a superpower disguised as boredom.",
  "You're closer than you were yesterday. Keep going.",
  "Revise what scares you most — that's where the marks hide.",
  "A missed day is a lesson, not a verdict. Restart today.",
  "Slow progress is still progress. Don't stop.",
  "Study like it's already your name with 'CA' in front of it.",
  "The hardest part is starting — so start, then continue.",
  "Doubts shrink the moment you attempt the question.",
  "Practice papers turn fear into familiarity.",
  "Sit down, open the book, and the mood will follow.",
  "You can rest when it's done. Right now, do the work.",
  "Comparison steals focus. Run your own race.",
  "What you practise in private, you perform in the exam.",
  "Be the student who finishes the chapter they started.",
  "Effort today is the cheapest investment in your career.",
  "Master the basics; toppers are just people with strong fundamentals.",
  "The grind is quiet, but the result is loud.",
  "Don't wish it were easier; work to make yourself better.",
  "Show up for the boring revision — that's where ranks are made.",
  "Your only competition is who you were yesterday.",
  "Write it by hand once; you'll remember it ten times longer.",
  "Confidence comes from preparation, not from pep talks.",
  "Finish strong: the last 10% of effort earns the first 10% of marks.",
  "Make peace with hard problems — they're your best teachers.",
  "A clear plan removes half the stress. Trust your plan.",
  "When in doubt, do one more question.",
  "You learned to walk by falling. You'll clear this the same way.",
  "Protect your mornings; that's when your brain is sharpest.",
  "Done is better than perfect. Complete the topic, then refine.",
  "The student who revises wins over the student who only learns.",
  "Big goals are reached one small session at a time.",
  "Stop scrolling, start solving. Five minutes is enough to begin.",
  "Your notes are a promise to your future self — keep it.",
  "Pressure is a privilege; it means you're chasing something worthwhile.",
  "Fall in love with the process and the result will follow.",
  "Mistakes in practice are free; make them now, not in the exam.",
  "Quiet effort, loud results.",
  "You've survived 100% of your hardest days so far.",
  "Treat each mock test like the real thing and the real thing like a mock.",
  "The syllabus is finite. Your persistence decides the rest.",
  "A focused hour beats a distracted four.",
  "Don't break the chain — one more day of study.",
  "Rank-holders also wanted to quit. They just didn't.",
  "Read less, recall more. Test yourself often.",
  "Your dream needs a deadline and a daily action. You have both.",
  "Discomfort is the price of growth. Pay it gladly.",
  "Keep your why bigger than your excuses.",
  "Today's revision is tomorrow's confidence.",
  "The best time to study was yesterday. The second best is now.",
  "Be relentless on the topics that carry the most marks.",
  "You don't rise to your goals; you fall to your habits. Build good ones.",
  "Finish the question even when it gets ugly — that's exam stamina.",
  "Drink water, sit straight, breathe — a sharp mind needs a steady body.",
  "Sleep is part of the syllabus; memory consolidates at night.",
  "A 10-minute walk resets a tired brain better than another coffee.",
  "Take the break before you're exhausted, not after.",
  "Eyes off the phone for one study block — feel the difference.",
  "Progress, not perfection. Keep the streak alive.",
  "The work you avoid is usually the work that matters most.",
  "Trust the hours. They add up even when you can't see it.",
  "Be patient with results and impatient with effort.",
  "Every solved question is a brick in your foundation.",
  "Calm mind, clear paper. Prepare so well that nerves have nothing to say.",
  "You're not behind; you're exactly where your effort has brought you. Now push.",
  "Turn 'I have to study' into 'I get to prepare for my future.'",
  "Champions do extra reps when no one is watching.",
  "Don't fear the tough chapter; respect it, then conquer it.",
  "One more revision round can change one grade — and one grade can change a lot.",
  "Momentum is built, not found. Start the first task.",
  "Your handwriting speed is a skill — train it before exam day.",
  "Aim to understand, not to memorise; understanding survives pressure.",
  "Energy follows attention. Put it on the work.",
  "Win the morning, win the day.",
  "Stay in your lane and your lane will take you to the result.",
  "The plan only works if you do. Open it and act.",
  "Hard work is the shortcut. There isn't another one.",
  "Be so prepared that the exam feels like a revision.",
  "A topic feared is a topic not yet practised enough.",
  "Doubt your doubts before you doubt your effort.",
  "Reward yourself for finishing, not for starting.",
  "The difference between dreaming and achieving is the daily to-do list.",
  "You can do anything for one more study session.",
  "Quiet consistency outlasts loud enthusiasm.",
  "Make today a day your future self thanks you for.",
  "Keep the goal in your heart and the next question in your hands.",
  "Tough exams build tough professionals. You're becoming one.",
  "Don't study harder when you can study smarter — test, review, repeat.",
  "Showing up is half the battle; you've already started winning.",
  "Two months of focus can outweigh two years of drifting.",
  "Stay humble in prep, confident in the exam.",
  "Your notes today are your lifeline in the last week.",
  "Failure is data. Adjust and go again.",
  "The marks you want are on the other side of the questions you're avoiding.",
  "Build the habit and the habit will build your result.",
  "There is no traffic on the extra mile — go there.",
  "Respect your study time like an appointment you can't miss.",
  "Be the reason your parents smile at the result.",
  "Steady hands, steady mind — practise until it's automatic.",
  "Don't let a bad hour become a bad day. Reset and continue.",
  "What feels impossible in week one feels routine by week six.",
  "Your effort is the one thing fully in your control. Spend it well.",
  "Prepare for the paper you fear and the rest will feel easy.",
  "Finish the revision you promised yourself this morning.",
  "Greatness is a lot of small, unglamorous, repeated efforts.",
  "Keep going — somewhere ahead, a future you is already celebrating.",
];
